"""database baseline

Revision ID: 20260813_0001
Revises:
Create Date: 2026-08-13 16:07:34.226577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260813_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_discovery_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategies', sa.JSON(), nullable=False),
    sa.Column('strategy_log', sa.JSON(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('discovered_market_count', sa.Integer(), nullable=False),
    sa.Column('registry_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('market_registry_sync_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_discovery_run_ids', sa.JSON(), nullable=False),
    sa.Column('checked_market_count', sa.Integer(), nullable=False),
    sa.Column('created_market_count', sa.Integer(), nullable=False),
    sa.Column('updated_market_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('orderbook_collection_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected_market_count', sa.Integer(), nullable=False),
    sa.Column('selected_token_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('polymarket_markets',
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('enable_order_book', sa.Boolean(), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_latest_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index('ix_polymarket_markets_collection_status', 'polymarket_markets', ['active', 'closed', 'archived'], unique=False)
    op.create_table('market_discovery_observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('discovery_run_id', sa.String(), nullable=False),
    sa.Column('proxy_wallet', sa.String(), nullable=True),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('held_token_id', sa.String(), nullable=False),
    sa.Column('opposite_token_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('opposite_outcome', sa.String(), nullable=False),
    sa.Column('position_size', sa.Numeric(), nullable=False),
    sa.Column('current_value', sa.Numeric(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_slug', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['market_discovery_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovery_observations_condition_observed', 'market_discovery_observations', ['condition_id', 'observed_at'], unique=False)
    op.create_index('ix_discovery_observations_discovery_run', 'market_discovery_observations', ['discovery_run_id'], unique=False)
    op.create_table('market_status_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('sync_run_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('enable_order_book', sa.Boolean(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['polymarket_markets.condition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['market_registry_sync_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_status_condition_checked', 'market_status_snapshots', ['condition_id', 'checked_at'], unique=False)
    op.create_table('orderbook_collection_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('market_status_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('api_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['orderbook_collection_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'token_id', name='uq_orderbook_item_run_token')
    )
    op.create_index('ix_orderbook_items_run', 'orderbook_collection_items', ['run_id'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exchange_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exchange_timestamp_raw', sa.String(), nullable=True),
    sa.Column('best_bid', sa.Numeric(), nullable=True),
    sa.Column('best_ask', sa.Numeric(), nullable=True),
    sa.Column('midpoint', sa.Numeric(), nullable=True),
    sa.Column('spread', sa.Numeric(), nullable=True),
    sa.Column('last_trade_price', sa.Numeric(), nullable=True),
    sa.Column('bid_depth_top_1', sa.Numeric(), nullable=True),
    sa.Column('ask_depth_top_1', sa.Numeric(), nullable=True),
    sa.Column('bid_depth_top_3', sa.Numeric(), nullable=True),
    sa.Column('ask_depth_top_3', sa.Numeric(), nullable=True),
    sa.Column('bid_depth_top_5', sa.Numeric(), nullable=True),
    sa.Column('ask_depth_top_5', sa.Numeric(), nullable=True),
    sa.Column('bid_levels_count', sa.Integer(), nullable=False),
    sa.Column('ask_levels_count', sa.Integer(), nullable=False),
    sa.Column('min_order_size', sa.Numeric(), nullable=True),
    sa.Column('tick_size', sa.Numeric(), nullable=True),
    sa.Column('negative_risk', sa.Boolean(), nullable=True),
    sa.Column('bids', sa.JSON(), nullable=False),
    sa.Column('asks', sa.JSON(), nullable=False),
    sa.Column('book_hash', sa.String(), nullable=True),
    sa.Column('valid_orderbook', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['orderbook_collection_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'token_id', name='uq_orderbook_snapshot_run_token')
    )
    op.create_index('ix_orderbook_snapshots_condition_generated', 'orderbook_snapshots', ['condition_id', 'generated_at'], unique=False)
    op.create_index('ix_orderbook_snapshots_token_generated', 'orderbook_snapshots', ['token_id', 'generated_at'], unique=False)
    op.create_index('ix_orderbook_snapshots_valid_generated', 'orderbook_snapshots', ['valid_orderbook', 'generated_at'], unique=False)
    op.create_table('polymarket_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('outcome_index', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_latest_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['polymarket_markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index('ix_polymarket_tokens_condition', 'polymarket_tokens', ['condition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_polymarket_tokens_condition', table_name='polymarket_tokens')
    op.drop_table('polymarket_tokens')
    op.drop_index('ix_orderbook_snapshots_valid_generated', table_name='orderbook_snapshots')
    op.drop_index('ix_orderbook_snapshots_token_generated', table_name='orderbook_snapshots')
    op.drop_index('ix_orderbook_snapshots_condition_generated', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index('ix_orderbook_items_run', table_name='orderbook_collection_items')
    op.drop_table('orderbook_collection_items')
    op.drop_index('ix_market_status_condition_checked', table_name='market_status_snapshots')
    op.drop_table('market_status_snapshots')
    op.drop_index('ix_discovery_observations_discovery_run', table_name='market_discovery_observations')
    op.drop_index('ix_discovery_observations_condition_observed', table_name='market_discovery_observations')
    op.drop_table('market_discovery_observations')
    op.drop_index('ix_polymarket_markets_collection_status', table_name='polymarket_markets')
    op.drop_table('polymarket_markets')
    op.drop_table('orderbook_collection_runs')
    op.drop_table('market_registry_sync_runs')
    op.drop_table('market_discovery_runs')
    # ### end Alembic commands ###
